- dockerfile: terraform.Dockerfile
  context: ./ci/docker/terraform
  platforms: linux/amd64,linux/arm64
  image_name: renvc-terraform
  project: renvc-dev

- dockerfile: test-engine.Dockerfile
  context: ./ci/docker/test-engine
  platforms: linux/amd64,linux/arm64
  image_name: test-engine
  project: renvc-dev

- dockerfile: eks-kubectl.Dockerfile
  context: ./ci/docker/eks-kubectl
  platforms: linux/amd64
  image_name: eks-kubectl
  project: renvc-prod

- dockerfile: nexus-sync.Dockerfile
  context: ./ci/docker/nexus-sync
  platforms: linux/amd64
  image_name: nexus-sync
  project: renvc-dev

- dockerfile: ivion-restore-tools.Dockerfile
  context: ./ci/docker/ivion-restore-tools
  platforms: linux/amd64
  image_name: ivion-restore-tools
  project: renvc-dev
