name: "[test] docker matrix generation"

on:
  pull_request:
    paths:
      - ci/docker/**

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          list-files: json
          filters: |
            docker:
              - 'ci/docker/**'
      - name: Debug changed files
        env:
          CHANGED_FILES: ${{ steps.filter.outputs.docker_files }}
        run: echo "$CHANGED_FILES" | jq .
      - id: build-matrix
        env:
          CHANGED_FILES: ${{ steps.filter.outputs.docker_files }}
        run: |
          ALL_BUILDS=$(yq -o=json ci/docker/builds.yaml)

          # extract list of image dirs that have changes, excluding README.md
          echo "$CHANGED_FILES" | jq -r '
            [.[] | ltrimstr("ci/docker/") | select(endswith("README.md") | not) | split("/")[0]] | unique | .[]
          ' > /tmp/changed_dirs

          # select builds for which the context matches a changed dir
          MATRIX=$(jq -cRn --arg config "$ALL_BUILDS" '
            [inputs] as $dirs |
            $config | fromjson |
            [.[] | select(.context | split("/")[-1] | IN($dirs[]))]
          ' /tmp/changed_dirs)
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  print-matrix:
    needs: build-matrix
    if: needs.build-matrix.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Print
        run: |
          echo "image:     ${{ matrix.build.image_name }}"
          echo "file:      ${{ matrix.build.dockerfile }}"
          echo "platforms: ${{ matrix.build.platforms }}"
          echo "project:   ${{ matrix.build.project }}"
